#!/bin/bash
echo -e "$OKORANGE + -- --=[GooHak v$VER by @xer0dayz, expanded by @gr4y-r0se$RESET"
echo -e "$OKORANGE + -- --=[Usage: goohak <domain>$RESET"
#
#ABOUT:
#GooHak is a shell script to automatically launch google hacking queries against a target domain to find vulnerabilities and enumerate a target.
#
#DEPENDENCIES:
#iceweasel or xdg-utils (apt-get install xdg-utils)
#Linux

TARGET="$1"
BROWSER="open" #CHANGE TO DEFAULT BROWSER - FOR OSX, USE "open".
VER="1.9"
OKBLUE='\033[94m'
OKRED='\033[91m'
OKGREEN='\033[92m'
OKORANGE='\033[93m'
DELAY=5
RESET='\e[0m'

echo "LOAD WEBSITE IN A WEB BROWSER"

$BROWSER http://$TARGET 2> /dev/null
$BROWSER https://$TARGET 2> /dev/null


echo "Checking TCPUTILS"
$BROWSER http://www.tcpiputils.com/browse/domain/$TARGET 2> /dev/null
echo "Checking NETCRAFT"
$BROWSER http://toolbar.netcraft.com/site_report?url=$TARGET 2> /dev/null
echo "Checking SHOWDAN"
$BROWSER "https://www.shodan.io/search?query=$TARGET" 2> /dev/null
echo "Checking CENSYS - Certificates"
$BROWSER https://search.censys.io/certificates?q=$TARGET 2> /dev/null
echo "Checking CENSYS - Hosts"
$BROWSER "https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=$TARGET"
echo "Checking DNSLYTICS"
$BROWSER "https://dnslytics.com/domain/$TARGET"
echo "Checking CRT.SH"
$BROWSER https://crt.sh/?q=%25.$TARGET 2> /dev/null
echo "Checking ZONE-H"
$BROWSER "https://www.google.ca/search?q=site:zone-h.org+$TARGET" 2> /dev/null
echo "Checking SECURITYHEADERS"
$BROWSER "https://securityheaders.io/?q=$TARGET" 2> /dev/null
echo "Checking SSLLABS"
$BROWSER https://www.ssllabs.com/ssltest/analyze.html?d=$TARGET 2> /dev/null
echo "Checking HEADER CHECK"
$BROWSER https://securityheaders.io/?q=$TARGET 2> /dev/null
echo "Checking THREATCROWD"
$BROWSER https://www.threatcrowd.org/domain.php?domain=$TARGET 2> /dev/null
echo "Checking ZOOMEYE"
$BROWSER https://www.zoomeye.org/searchResult/bugs?q=$TARGET 2> /dev/null
echo "Checking DOMAIN INFO SEARCH"
$BROWSER https://securitytrails.com/domain/$TARGET/dns 2> /dev/null
echo "Checking WAYBACKMACHINE"
$BROWSER https://web.archive.org/web/*/$TARGET 2> /dev/null
echo "Checking REVERSEDNS"
$BROWSER http://viewdns.info/reversewhois/?q=$TARGET 2> /dev/null
echo "Checking PUNKSPIDER"
$BROWSER "https://www.punkspider.org/#searchkey=url&searchvalue=$TARGET&pagenumber=1&filterType=or" 2> /dev/null

sleep $DELAY
echo "Checking FIND SUBDOMAINS"
$BROWSER "https://www.google.ca/search?q=site:*.$TARGET" 2> /dev/null
$BROWSER "https://www.google.ca/search?q=site:*.*.$TARGET" 2> /dev/null

sleep $DELAY
echo "Checking FIND LOGIN PAGES:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+username+OR+password+OR+login+OR+root+OR+admin" 2> /dev/null
echo "Checking SEARCH FOR BACKDOORS:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:shell+OR+inurl:backdoor+OR+inurl:wso+OR+inurl:cmd+OR+shadow+OR+passwd+OR+boot.ini+OR+inurl:backdoor" 2> /dev/null
echo "Checking FIND SETUP OR INSTALL FILES:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:readme+OR+inurl:license+OR+inurl:install+OR+inurl:setup+OR+inurl:config" 2> /dev/null
echo "Checking FIND WORDPRESS PLUGINS/UPLOADS/DOWNLOADS:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:wp-+OR+inurl:plugin+OR+inurl:upload+OR+inurl:download" 2> /dev/null
echo "Checking FIND OPEN REDIRECTS:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:redir+OR+inurl:url+OR+inurl:redirect+OR+inurl:return+OR+inurl:src=http+OR+inurl:r=http" 2> /dev/null

sleep $DELAY

echo "Checking s3 bucket stuff"
domain=$(echo $TARGET | cut -d '.' -f 1)
$BROWSER https://$domain.s3.amazonaws.com 2> /dev/null
$BROWSER https://s3.amazonaws.com/$domain 2> /dev/null
echo "Checking for sharepoint presence"
$BROWSER https://$domain.sharepoint.com 2> /dev/null

sleep $DELAY
echo "Copyright checks"
$BROWSER "https://www.google.com/search?q=%22Copyright, $domain, 20%22 -$TARGET"

sleep $DELAY
echo "Checking FIND FILES BY EXTENSION:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:cgi+OR+ext:php+OR+ext:asp+OR+ext:aspx+OR+ext:jsp+OR+ext:jspx+OR+ext:swf+OR+ext:fla+OR+ext:xml" 2> /dev/null
echo "Checking FIND DOCUMENTS BY EXTENSION:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:doc+OR+ext:docx+OR+ext:csv+OR+ext:pdf+OR+ext:txt+OR+ext:log+OR+ext:bak" 2> /dev/null
echo "Checking FIND APACHE STRUTS RCE's:"
$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:action+OR+struts" 2> /dev/null
echo "Checking FIND PASTEBIN POSTS FOR DOMAIN:"
$BROWSER "https://www.google.ca/search?q=site:pastebin.com+$TARGET" 2> /dev/null
echo "Checking FIND EMPLOYEES ON LINKEDIN:"
$BROWSER "https://www.google.ca/search?q=site:linkedin.com+employees+$TARGET" 2> /dev/null
