#!/bin/bash
# + -- --=[Hackgoo v1.6 by ZephrFish
# + -- --=[Modified for OSX Compatability
# + -- --=[sed 's/iceweasel/open/g' goohak > hackgoo
#
# ABOUT:
# GooHak is a shell script to automatically launch google hacking queries against a target domain to find vulnerabilities and enumerate a target.
#
# DEPENDENCIES:
# open
# Linux

TARGET="$1"
OKBLUE='\033[94m'
OKRED='\033[91m'
OKGREEN='\033[92m'
OKORANGE='\033[93m'
RESET='\e[0m'

if [ -z $TARGET ]; then
	echo -e "+ -- --=[Hackgoo v1.6 by ZephrFish"
  echo -e "+ -- --=[Modified for OSX Compatability"
  echo -e "+ -- --=[sed 's/iceweasel/open/g' goohak > hackgoo"
	exit
fi

open 2> /dev/null &
sleep 5

# Google Dorks
echo "Opening Browser with search terms per tab"

# FIND LOGIN PAGES:
open "https://www.google.ca/search?q=site:$TARGET+username+OR+password+OR+login+OR+root+OR+admin" 2> /dev/null
# SEARCH FOR BACKDOORS:
open "https://www.google.ca/search?q=site:$TARGET+inurl:shell+OR+inurl:backdoor+OR+inurl:wso+OR+inurl:cmd+OR+shadow+OR+passwd+OR+boot.ini+OR+inurl:backdoor" 2> /dev/null
# FIND SETUP OR INSTALL FILES:
open "https://www.google.ca/search?q=site:$TARGET+inurl:readme+OR+inurl:license+OR+inurl:install+OR+inurl:setup+OR+inurl:config" 2> /dev/null
# FIND WORDPRESS PLUGINS/UPLOADS/DOWNLOADS:
open "https://www.google.ca/search?q=site:$TARGET+inurl:wp-+OR+inurl:plugin+OR+inurl:upload+OR+inurl:download" 2> /dev/null
# FIND OPEN REDIRECTS:
open "https://www.google.ca/search?q=site:$TARGET+inurl:redir+OR+inurl:url+OR+inurl:redirect+OR+inurl:return+OR+inurl:src=http+OR+inurl:r=http" 2> /dev/null
# FIND FILES BY EXTENSION:
open "https://www.google.ca/search?q=site:$TARGET+ext:cgi+OR+ext:php+OR+ext:asp+OR+ext:aspx+OR+ext:jsp+OR+ext:jspx+OR+ext:swf+OR+ext:fla+OR+ext:xml" 2> /dev/null
# FIND DOCUMENTS BY EXTENSION:
open "https://www.google.ca/search?q=site:$TARGET+ext:doc+OR+ext:docx+OR+ext:csv+OR+ext:pdf+OR+ext:txt+OR+ext:log+OR+ext:bak" 2> /dev/null
# FIND APACHE STRUTS RCE's:
open "https://www.google.ca/search?q=site:$TARGET+ext:action+OR+ext:struts" 2> /dev/null
# FIND PASTEBIN POSTS FOR DOMAIN:
open "https://www.google.ca/search?q=site:pastebin.com+$TARGET" 2> /dev/null
# FIND EMPLOYEES ON LINKEDIN:
open "https://www.google.ca/search?q=site:linkedin.com+employees+$TARGET" 2> /dev/null

# Find Subdomains
open "https://www.google.ca/search?q=site:*.$TARGET" 2> /dev/null

# Find Sub-subdomains
open "https://www.google.ca/search?q=site:*.*.$TARGET" 2> /dev/null
